echo [INFO] ----------Converting glsl to spv file...
..\..\External\exe\vulkan\glslc.exe shader.vert -o vertex.spv
..\..\External\exe\vulkan\glslc.exe shader.frag -o fragment.spv
echo [INFO] ----------Converting Done...